# Generated by Django 6.0.4 on 2026-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sessionnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_preference',
            field=models.CharField(default='self_guided', max_length=20),
        ),
    ]
