# Generated by Django 6.0.4 on 2026-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_session_preference'),
        ('analytics', '0003_delete_childactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentalcontrol',
            name='child',
        ),
        migrations.RemoveField(
            model_name='parentalcontrol',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('therapist', 'user')},
        ),
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(choices=[('teen', 'Teen'), ('adult', 'Adult'), ('senior', 'Senior')], default='adult', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('therapist', 'Therapist')], default='individual', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChildProfile',
        ),
        migrations.DeleteModel(
            name='ParentalControl',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='child',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='parent',
        ),
    ]
