# Generated by Django 6.0.4 on 2026-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_parentalcontrol_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinical_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
