# Generated by Django 6.0.4 on 2026-04-10 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('adhd', 'ADHD'), ('anxiety', 'Anxiety'), ('autism', 'Autism'), ('general', 'General')], max_length=20)),
                ('type', models.CharField(choices=[('focus', 'Focus'), ('memory', 'Memory'), ('calming', 'Calming'), ('pattern', 'Pattern'), ('reaction', 'Reaction')], max_length=20)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('stimulation_level', models.IntegerField(default=5)),
                ('time_pressure', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('mood_before', models.IntegerField(blank=True, null=True)),
                ('mood_after', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
