# Generated by Django 6.0.4 on 2026-04-08 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('anxiety', 'Anxiety (GAD-7)'), ('depression', 'Depression (PHQ-9)'), ('adhd', 'ADHD Screening'), ('stress', 'Stress (PSS)')], max_length=30)),
                ('responses', models.JSONField(help_text='Raw answer key-value pairs from the questionnaire')),
                ('score', models.IntegerField(default=0)),
                ('severity', models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], max_length=25)),
                ('notes', models.TextField(blank=True, help_text='Auto-generated or therapist notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
