# Generated by Django 6.0.4 on 2026-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('anxiety', 'Anxiety (GAD-7)'), ('depression', 'Depression (PHQ-9)'), ('adhd', 'ADHD Screening'), ('stress', 'Stress (PSS)')], max_length=30)),
                ('question_key', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('scale', models.CharField(choices=[('0-3', '0 to 3 (GAD-7 / PHQ-9 style)'), ('1-5', '1 to 5'), ('0-4', '0 to 4'), ('never-always', 'Never to Always')], default='0-3', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['condition', 'order'],
                'unique_together': {('condition', 'question_key')},
            },
        ),
    ]
