# Generated by Django 6.0.4 on 2026-04-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_option_usercognitiveprofile_userresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
    ]
