# Generated by Django 6.0.4 on 2026-04-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_childactivity_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildActivity',
        ),
    ]
